name: Test

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 22 * * 3'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '20.10'
          - '18.18'
          - '16.20'
        os:
          - macos-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "${{ matrix.node-version }}"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
  test-docker:
    name: Test Linux
    strategy:
      matrix:
        node-version:
          - '20.10'
          - '18.18'
          - '16.20'
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build Test Image
        run: yarn build:docker
        env:
          NODE_VERSION: "${{ matrix.node-version }}"
      - name: Test in Docker Container
        run: yarn test:docker
        env:
          NODE_VERSION: "${{ matrix.node-version }}"